apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: demo-voting-app
spec:
  containers:
    - name: postgres
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: votingapp
